import type { Metadata } from "next";
import "./globals.css";
// import Providers from "@/Providers/Provider";
import { Toaster } from "sonner";
import Providers from "@/Providers/Provider";

export const metadata: Metadata = {
  title: "Home Renting System",
  description: "Generated by  next.js app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className="min-h-screen bg-zinc-900 font-sans">
          {children}
          <Toaster />
        </body>
      </html>
    </Providers>
  );
}
